### Buscar todos os professores
GET http://localhost:3000/api/v1/professores

### Buscar professor pelo ID
GET http://localhost:3000/api/v1/professores/03142934-b6a4-4576-b3a4-ea4166899570

### Inserir um novo professor
POST http://localhost:3000/api/v1/professores
Content-Type: application/json

{
  "nome": "João",
  "materia": "Direção defensiva"
}

### Atualizar um professor
PUT http://localhost:3000/api/v1/professores/b2efdc76-c124-4d97-b965-e696a3681f9e
Content-Type: application/json

{
  "nome": "Jeferson",
  "materia": "Primeiros-socorros"
}

### Remover um professor
DELETE  http://localhost:3000/api/v1/professores/03142934-b6a4-4576-b3a4-ea4166899570
Content-Type: application/json